spring.application.name: customers-and-orders-spring-authorization-server

server:
  port: 9000

logging:
  level:
    org.springframework.security: trace

management.endpoints.web.exposure.include: health
management.endpoint.health.show-details: always
management.endpoint.health.access: unrestricted

spring:
  security:
    user:
      name: user1
      password: password
    oauth2:
      authorizationserver:
        client:
          messaging-client:
            registration:
              client-id: "messaging-client"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
                - "client_credentials"
                - "password"
              redirect-uris:
                - "http://127.0.0.1:8080/login/oauth2/code/messaging-client-oidc"
                - "http://127.0.0.1:8080/authorized"
                - "http://localhost:3000/api/auth/callback/oauth2-pkce"
              post-logout-redirect-uris:
                - "http://127.0.0.1:8080/logged-out"
              scopes:
                - "openid"
                - "profile"
                - "email"
                - "message.read"
                - "message.write"
            require-authorization-consent: true
            require-proof-key: true
