name: Build, Test, and Publish Docker Image

on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'

jobs:
  build_test_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          cache-read-only: false

      - name: Build application
        run: ./gradlew build

      - name: Set up QEMU for multi-architecture support
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Define image tag
        id: image_tag
        run: |
          if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            TAG=${{ github.ref_name }}
          else
            TAG=$(git rev-parse --short HEAD)
          fi
          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV

      - name: Build and push image to local registry for testing
        run: ./gradlew buildDockerImageLocally -P imageVersion=$IMAGE_TAG

      - name: Run integration tests with Testcontainers
        run: ./gradlew integrationTest -P dockerImage=localhost:5000/customers-and-orders-spring-authorization-server:$IMAGE_TAG

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Copy the tested image to Docker Hub
        run: |
          docker buildx imagetools create \
            --tag eventuateio/customers-and-orders-spring-authorization-server:$IMAGE_TAG \
            localhost:5000/myapp:$IMAGE_TAG
